<?php

namespace Esprit\RubriqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository {

    public function findOneByIdJoinedToRubrique($id) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT d, r FROM EspritRubriqueBundle:Document d
            JOIN d.rubrique r
            WHERE d.id = :id'
                        )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
