esprit_rubrique_homepage:
    pattern:  /
    defaults: { _controller: EspritRubriqueBundle:Document:index }
EspritRubriqueBundle_rubrique:
    resource: "@EspritRubriqueBundle/Resources/config/routing/rubrique.yml"
    prefix:   /rubrique
EspritRubriqueBundle_document:
    resource: "@EspritRubriqueBundle/Resources/config/routing/document.yml"
    prefix:   /document