parameters:
#    esprit_rubrique.example.class: Esprit\RubriqueBundle\Example

services:
#    esprit_rubrique.example:
#        class: %esprit_rubrique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
