parameters:
    database_driver:   oci8
    database_host:     abdelaziz-TOSH
    database_port:     1521
    database_name:     XE
    database_user:     esprit
    database_password: esprit

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
