<?php

namespace Esprit\RubriqueBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DocumentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\RubriqueBundle\Controller\DocumentController();
        return $instance;
    }
}
