sdzblog_accueil:
    pattern:   /
    defaults:  { _controller: AcmeDemoBundle:Demo:index }
etudiant_eol:
    pattern:   /etudiant
    defaults:  { _controller: AcmeDemoBundle:Demo:contact }
admin_eol:
    pattern:   /admin
    defaults:  { _controller: AcmeDemoBundle:Demo:index }
  
  